import { CategoryPreset, mm } from "../core/types";

export const categoryDimensionRules: Record<
  CategoryPreset["category"],
  CategoryPreset["dimensionOverrides"]
> = {
  Pistol: {
    receiver: {
      minLength: mm(145),
      maxLength: mm(190),
      minWidth: mm(30),
      maxWidth: mm(40),
    },
    barrel: {
      minLength: mm(75),
      maxLength: mm(118),
      minWidth: mm(12),
      maxWidth: mm(18),
    },
    magwell: {
      minLength: mm(48),
      maxLength: mm(72),
      minWidth: mm(22),
      maxWidth: mm(30),
    },
    magazine: {
      minLength: mm(95),
      maxLength: mm(165),
      minWidth: mm(18),
      maxWidth: mm(26),
    },
    pistolGrip: {
      minLength: mm(88),
      maxLength: mm(112),
      minWidth: mm(24),
      maxWidth: mm(32),
    },
    handguard: {
      minLength: mm(0),
      maxLength: mm(40),
      minWidth: mm(30),
      maxWidth: mm(40),
    },
    optic: {
      minLength: mm(40),
      maxLength: mm(62),
      minWidth: mm(22),
      maxWidth: mm(30),
    },
    muzzleDevice: {
      minLength: mm(18),
      maxLength: mm(35),
      minWidth: mm(22),
      maxWidth: mm(32),
    },
    stock: { minLength: mm(0), maxLength: mm(0) },
  },
  SMG: {
    receiver: {
      minLength: mm(175),
      maxLength: mm(245),
      minWidth: mm(38),
      maxWidth: mm(52),
    },
    barrel: {
      minLength: mm(110),
      maxLength: mm(190),
      minWidth: mm(12),
      maxWidth: mm(18),
    },
    magwell: {
      minLength: mm(55),
      maxLength: mm(80),
      minWidth: mm(24),
      maxWidth: mm(34),
    },
    magazine: {
      minLength: mm(130),
      maxLength: mm(260),
      minWidth: mm(20),
      maxWidth: mm(32),
    },
    pistolGrip: {
      minLength: mm(90),
      maxLength: mm(118),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(55),
      maxLength: mm(135),
      minWidth: mm(32),
      maxWidth: mm(46),
    },
    optic: {
      minLength: mm(40),
      maxLength: mm(92),
      minWidth: mm(25),
      maxWidth: mm(34),
    },
    muzzleDevice: {
      minLength: mm(20),
      maxLength: mm(45),
      minWidth: mm(22),
      maxWidth: mm(34),
    },
    stock: {
      minLength: mm(125),
      maxLength: mm(195),
      minWidth: mm(38),
      maxWidth: mm(58),
    },
  },
  Carbine: {
    receiver: {
      minLength: mm(210),
      maxLength: mm(280),
      minWidth: mm(40),
      maxWidth: mm(51),
    },
    barrel: {
      minLength: mm(220),
      maxLength: mm(315),
      minWidth: mm(14),
      maxWidth: mm(19),
    },
    magwell: {
      minLength: mm(58),
      maxLength: mm(82),
      minWidth: mm(24),
      maxWidth: mm(34),
    },
    magazine: {
      minLength: mm(145),
      maxLength: mm(220),
      minWidth: mm(22),
      maxWidth: mm(32),
    },
    pistolGrip: {
      minLength: mm(92),
      maxLength: mm(120),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(140),
      maxLength: mm(230),
      minWidth: mm(34),
      maxWidth: mm(45),
    },
    optic: {
      minLength: mm(45),
      maxLength: mm(110),
      minWidth: mm(26),
      maxWidth: mm(36),
    },
    muzzleDevice: {
      minLength: mm(20),
      maxLength: mm(45),
      minWidth: mm(22),
      maxWidth: mm(36),
    },
    stock: {
      minLength: mm(150),
      maxLength: mm(220),
      minWidth: mm(40),
      maxWidth: mm(53),
    },
  },
  AssaultRifle: {
    receiver: {
      minLength: mm(225),
      maxLength: mm(300),
      minWidth: mm(42),
      maxWidth: mm(56),
    },
    barrel: {
      minLength: mm(280),
      maxLength: mm(390),
      minWidth: mm(14),
      maxWidth: mm(21),
    },
    magwell: {
      minLength: mm(60),
      maxLength: mm(86),
      minWidth: mm(24),
      maxWidth: mm(36),
    },
    magazine: {
      minLength: mm(160),
      maxLength: mm(240),
      minWidth: mm(22),
      maxWidth: mm(34),
    },
    pistolGrip: {
      minLength: mm(94),
      maxLength: mm(122),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(170),
      maxLength: mm(275),
      minWidth: mm(34),
      maxWidth: mm(50),
    },
    optic: {
      minLength: mm(50),
      maxLength: mm(118),
      minWidth: mm(26),
      maxWidth: mm(38),
    },
    muzzleDevice: {
      minLength: mm(22),
      maxLength: mm(48),
      minWidth: mm(22),
      maxWidth: mm(38),
    },
    stock: {
      minLength: mm(170),
      maxLength: mm(240),
      minWidth: mm(42),
      maxWidth: mm(62),
    },
  },
  BattleRifle: {
    receiver: {
      minLength: mm(235),
      maxLength: mm(315),
      minWidth: mm(44),
      maxWidth: mm(58),
    },
    barrel: {
      minLength: mm(330),
      maxLength: mm(450),
      minWidth: mm(15),
      maxWidth: mm(22),
    },
    magwell: {
      minLength: mm(62),
      maxLength: mm(90),
      minWidth: mm(26),
      maxWidth: mm(38),
    },
    magazine: {
      minLength: mm(165),
      maxLength: mm(240),
      minWidth: mm(24),
      maxWidth: mm(36),
    },
    pistolGrip: {
      minLength: mm(94),
      maxLength: mm(122),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(185),
      maxLength: mm(290),
      minWidth: mm(36),
      maxWidth: mm(52),
    },
    optic: {
      minLength: mm(60),
      maxLength: mm(135),
      minWidth: mm(28),
      maxWidth: mm(40),
    },
    muzzleDevice: {
      minLength: mm(22),
      maxLength: mm(52),
      minWidth: mm(22),
      maxWidth: mm(40),
    },
    stock: {
      minLength: mm(180),
      maxLength: mm(250),
      minWidth: mm(42),
      maxWidth: mm(64),
    },
  },
  DMR: {
    receiver: {
      minLength: mm(240),
      maxLength: mm(325),
      minWidth: mm(44),
      maxWidth: mm(58),
    },
    barrel: {
      minLength: mm(420),
      maxLength: mm(540),
      minWidth: mm(16),
      maxWidth: mm(23),
    },
    magwell: {
      minLength: mm(62),
      maxLength: mm(90),
      minWidth: mm(26),
      maxWidth: mm(38),
    },
    magazine: {
      minLength: mm(160),
      maxLength: mm(230),
      minWidth: mm(24),
      maxWidth: mm(36),
    },
    pistolGrip: {
      minLength: mm(94),
      maxLength: mm(122),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(200),
      maxLength: mm(310),
      minWidth: mm(36),
      maxWidth: mm(52),
    },
    optic: {
      minLength: mm(110),
      maxLength: mm(180),
      minWidth: mm(28),
      maxWidth: mm(42),
    },
    muzzleDevice: {
      minLength: mm(22),
      maxLength: mm(55),
      minWidth: mm(22),
      maxWidth: mm(42),
    },
    stock: {
      minLength: mm(190),
      maxLength: mm(265),
      minWidth: mm(44),
      maxWidth: mm(66),
    },
  },
  Sniper: {
    receiver: {
      minLength: mm(285),
      maxLength: mm(370),
      minWidth: mm(46),
      maxWidth: mm(60),
    },
    barrel: {
      minLength: mm(520),
      maxLength: mm(620),
      minWidth: mm(18),
      maxWidth: mm(24),
    },
    magwell: {
      minLength: mm(58),
      maxLength: mm(84),
      minWidth: mm(24),
      maxWidth: mm(36),
    },
    magazine: {
      minLength: mm(120),
      maxLength: mm(190),
      minWidth: mm(22),
      maxWidth: mm(34),
    },
    pistolGrip: {
      minLength: mm(96),
      maxLength: mm(124),
      minWidth: mm(26),
      maxWidth: mm(34),
    },
    handguard: {
      minLength: mm(220),
      maxLength: mm(340),
      minWidth: mm(38),
      maxWidth: mm(56),
    },
    optic: {
      minLength: mm(135),
      maxLength: mm(185),
      minWidth: mm(30),
      maxWidth: mm(46),
    },
    muzzleDevice: {
      minLength: mm(24),
      maxLength: mm(70),
      minWidth: mm(24),
      maxWidth: mm(44),
    },
    stock: {
      minLength: mm(230),
      maxLength: mm(320),
      minWidth: mm(46),
      maxWidth: mm(70),
    },
  },
};
