import { CategoryPreset, mm } from "../core/types";

export const categoryDimensionRules: Record<
  CategoryPreset["category"],
  CategoryPreset["dimensionOverrides"]
> = {
  Pistol: {
    receiver: {
      minSizeX: mm(145),
      maxSizeX: mm(190),
      minSizeY: mm(30),
      maxSizeY: mm(40),
    },
    barrel: {
      minSizeX: mm(75),
      maxSizeX: mm(118),
      minSizeY: mm(12),
      maxSizeY: mm(18),
    },
    magwell: {
      minSizeX: mm(48),
      maxSizeX: mm(72),
      minSizeY: mm(22),
      maxSizeY: mm(30),
    },
    magazine: {
      minSizeX: mm(18),
      maxSizeX: mm(26),
      minSizeY: mm(95),
      maxSizeY: mm(165),
    },
    pistolGrip: {
      minSizeX: mm(24),
      maxSizeX: mm(32),
      minSizeY: mm(88),
      maxSizeY: mm(112),
    },
    handguard: {
      minSizeX: mm(0),
      maxSizeX: mm(40),
      minSizeY: mm(30),
      maxSizeY: mm(40),
    },
    optic: {
      minSizeX: mm(40),
      maxSizeX: mm(62),
      minSizeY: mm(22),
      maxSizeY: mm(30),
    },
    muzzleDevice: {
      minSizeX: mm(18),
      maxSizeX: mm(35),
      minSizeY: mm(22),
      maxSizeY: mm(32),
    },
    stock: { minSizeX: mm(0), maxSizeX: mm(0) },
  },
  SMG: {
    receiver: {
      minSizeX: mm(175),
      maxSizeX: mm(245),
      minSizeY: mm(38),
      maxSizeY: mm(52),
    },
    barrel: {
      minSizeX: mm(110),
      maxSizeX: mm(190),
      minSizeY: mm(12),
      maxSizeY: mm(18),
    },
    magwell: {
      minSizeX: mm(55),
      maxSizeX: mm(80),
      minSizeY: mm(24),
      maxSizeY: mm(34),
    },
    magazine: {
      minSizeX: mm(20),
      maxSizeX: mm(32),
      minSizeY: mm(130),
      maxSizeY: mm(260),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(90),
      maxSizeY: mm(118),
    },
    handguard: {
      minSizeX: mm(55),
      maxSizeX: mm(135),
      minSizeY: mm(32),
      maxSizeY: mm(46),
    },
    optic: {
      minSizeX: mm(40),
      maxSizeX: mm(92),
      minSizeY: mm(25),
      maxSizeY: mm(34),
    },
    muzzleDevice: {
      minSizeX: mm(20),
      maxSizeX: mm(45),
      minSizeY: mm(22),
      maxSizeY: mm(34),
    },
    stock: {
      minSizeX: mm(125),
      maxSizeX: mm(195),
      minSizeY: mm(38),
      maxSizeY: mm(58),
    },
  },
  Carbine: {
    receiver: {
      minSizeX: mm(210),
      maxSizeX: mm(280),
      minSizeY: mm(40),
      maxSizeY: mm(51),
    },
    barrel: {
      minSizeX: mm(220),
      maxSizeX: mm(315),
      minSizeY: mm(14),
      maxSizeY: mm(19),
    },
    magwell: {
      minSizeX: mm(58),
      maxSizeX: mm(82),
      minSizeY: mm(24),
      maxSizeY: mm(34),
    },
    magazine: {
      minSizeX: mm(22),
      maxSizeX: mm(32),
      minSizeY: mm(145),
      maxSizeY: mm(220),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(92),
      maxSizeY: mm(120),
    },
    handguard: {
      minSizeX: mm(140),
      maxSizeX: mm(230),
      minSizeY: mm(34),
      maxSizeY: mm(45),
    },
    optic: {
      minSizeX: mm(45),
      maxSizeX: mm(110),
      minSizeY: mm(26),
      maxSizeY: mm(36),
    },
    muzzleDevice: {
      minSizeX: mm(20),
      maxSizeX: mm(45),
      minSizeY: mm(22),
      maxSizeY: mm(36),
    },
    stock: {
      minSizeX: mm(150),
      maxSizeX: mm(220),
      minSizeY: mm(40),
      maxSizeY: mm(53),
    },
  },
  AssaultRifle: {
    receiver: {
      minSizeX: mm(225),
      maxSizeX: mm(300),
      minSizeY: mm(42),
      maxSizeY: mm(56),
    },
    barrel: {
      minSizeX: mm(280),
      maxSizeX: mm(390),
      minSizeY: mm(14),
      maxSizeY: mm(21),
    },
    magwell: {
      minSizeX: mm(60),
      maxSizeX: mm(86),
      minSizeY: mm(24),
      maxSizeY: mm(36),
    },
    magazine: {
      minSizeX: mm(22),
      maxSizeX: mm(34),
      minSizeY: mm(160),
      maxSizeY: mm(240),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(94),
      maxSizeY: mm(122),
    },
    handguard: {
      minSizeX: mm(170),
      maxSizeX: mm(275),
      minSizeY: mm(34),
      maxSizeY: mm(50),
    },
    optic: {
      minSizeX: mm(50),
      maxSizeX: mm(118),
      minSizeY: mm(26),
      maxSizeY: mm(38),
    },
    muzzleDevice: {
      minSizeX: mm(22),
      maxSizeX: mm(48),
      minSizeY: mm(22),
      maxSizeY: mm(38),
    },
    stock: {
      minSizeX: mm(170),
      maxSizeX: mm(240),
      minSizeY: mm(42),
      maxSizeY: mm(62),
    },
  },
  BattleRifle: {
    receiver: {
      minSizeX: mm(235),
      maxSizeX: mm(315),
      minSizeY: mm(44),
      maxSizeY: mm(58),
    },
    barrel: {
      minSizeX: mm(330),
      maxSizeX: mm(450),
      minSizeY: mm(15),
      maxSizeY: mm(22),
    },
    magwell: {
      minSizeX: mm(62),
      maxSizeX: mm(90),
      minSizeY: mm(26),
      maxSizeY: mm(38),
    },
    magazine: {
      minSizeX: mm(24),
      maxSizeX: mm(36),
      minSizeY: mm(165),
      maxSizeY: mm(240),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(94),
      maxSizeY: mm(122),
    },
    handguard: {
      minSizeX: mm(185),
      maxSizeX: mm(290),
      minSizeY: mm(36),
      maxSizeY: mm(52),
    },
    optic: {
      minSizeX: mm(60),
      maxSizeX: mm(135),
      minSizeY: mm(28),
      maxSizeY: mm(40),
    },
    muzzleDevice: {
      minSizeX: mm(22),
      maxSizeX: mm(52),
      minSizeY: mm(22),
      maxSizeY: mm(40),
    },
    stock: {
      minSizeX: mm(180),
      maxSizeX: mm(250),
      minSizeY: mm(42),
      maxSizeY: mm(64),
    },
  },
  DMR: {
    receiver: {
      minSizeX: mm(240),
      maxSizeX: mm(325),
      minSizeY: mm(44),
      maxSizeY: mm(58),
    },
    barrel: {
      minSizeX: mm(420),
      maxSizeX: mm(540),
      minSizeY: mm(16),
      maxSizeY: mm(23),
    },
    magwell: {
      minSizeX: mm(62),
      maxSizeX: mm(90),
      minSizeY: mm(26),
      maxSizeY: mm(38),
    },
    magazine: {
      minSizeX: mm(24),
      maxSizeX: mm(36),
      minSizeY: mm(160),
      maxSizeY: mm(230),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(94),
      maxSizeY: mm(122),
    },
    handguard: {
      minSizeX: mm(200),
      maxSizeX: mm(310),
      minSizeY: mm(36),
      maxSizeY: mm(52),
    },
    optic: {
      minSizeX: mm(110),
      maxSizeX: mm(180),
      minSizeY: mm(28),
      maxSizeY: mm(42),
    },
    muzzleDevice: {
      minSizeX: mm(22),
      maxSizeX: mm(55),
      minSizeY: mm(22),
      maxSizeY: mm(42),
    },
    stock: {
      minSizeX: mm(190),
      maxSizeX: mm(265),
      minSizeY: mm(44),
      maxSizeY: mm(66),
    },
  },
  Sniper: {
    receiver: {
      minSizeX: mm(285),
      maxSizeX: mm(370),
      minSizeY: mm(46),
      maxSizeY: mm(60),
    },
    barrel: {
      minSizeX: mm(520),
      maxSizeX: mm(620),
      minSizeY: mm(18),
      maxSizeY: mm(24),
    },
    magwell: {
      minSizeX: mm(58),
      maxSizeX: mm(84),
      minSizeY: mm(24),
      maxSizeY: mm(36),
    },
    magazine: {
      minSizeX: mm(22),
      maxSizeX: mm(34),
      minSizeY: mm(120),
      maxSizeY: mm(190),
    },
    pistolGrip: {
      minSizeX: mm(26),
      maxSizeX: mm(34),
      minSizeY: mm(96),
      maxSizeY: mm(124),
    },
    handguard: {
      minSizeX: mm(220),
      maxSizeX: mm(340),
      minSizeY: mm(38),
      maxSizeY: mm(56),
    },
    optic: {
      minSizeX: mm(135),
      maxSizeX: mm(185),
      minSizeY: mm(30),
      maxSizeY: mm(46),
    },
    muzzleDevice: {
      minSizeX: mm(24),
      maxSizeX: mm(70),
      minSizeY: mm(24),
      maxSizeY: mm(44),
    },
    stock: {
      minSizeX: mm(230),
      maxSizeX: mm(320),
      minSizeY: mm(46),
      maxSizeY: mm(70),
    },
  },
};
